########## default ##########
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /

logging:
  level:
    com.dineug.file: off

#dineug config
dineug:
  env: ${spring.profiles.active}
  azure:
    blob: 이름
    key: DefaultEndpointsProtocol=https;AccountName=이름;AccountKey=키
  

########## test ##########
---
spring:
  profiles: test

logging:
  level:
    com.dineug.file: debug


########## localhost ##########
---
spring:
  profiles: local

logging:
  level:
    com.dineug.file: debug


########## development ##########
---
spring:
  profiles: dev

logging:
  level:
    com.dineug.file: debug


########## production ##########
---
spring:
  profiles: prod
  